### PR TITLE
Update responsive new atd version

### PR DESCRIPTION
**Pull request by blackinno**
#75

### CODE REVIEW

**Comment by EmmanuelDrouin** [comment]
Still few modifications to do but the responsive start to look nice ;)

First thing we should have the desktop version on a 1024px width screen.

For the mobile version: from ... to 768px
For the Desktop version: from 769px to ...

**On the desktop version:**

You still have some issues with the margin or padding inside the locked wallet and there is a missing margin between the title and the cards.

Screenshot 2019-09-17 at 14 01 52

**On the mobile version:** 

We should improve the margin between elements, they are too small.

The size of the content inside the cards "locked wallet" are really small (title and paragraphe). it's gonna be really complicated to read, you should not decrease the size so much from the desktop version.

The title (h1) should have more top and bottom margin so it won't look like it's struggle inside the background
.
Screenshot 2019-09-17 at 13 58 04

We need more space between the elements (margin), you can double at least 40px.
Screenshot 2019-09-17 at 13 56 15
Screenshot 2019-09-17 at 13 56 25
Screenshot 2019-09-17 at 13 56 45

Also the elements are not align, if you look at the menu, the title and the cards for exemple you will see that you are actually losing space and it look wired.
Screenshot 2019-09-17 at 13 58 31
Screenshot 2019-09-17 at 13 58 56

You also have an issue with the logo in the footer, it's really big ^^.
Screenshot 2019-09-17 at 13 59 00

**Comment by EmmanuelDrouin** [comment]
Nice touch for the menu :)

In General i recommend you to use padding instead of margin when you want to give some space to the content inside an element (Container, Cards, etc.). You should use margin only  to separate an element from another one.

Screenshot 2019-09-18 at 16 58 54
Screenshot 2019-09-18 at 16 59 05

**Desktop version:**

Locked wallets:
You should use the total width for your container. there is no need to add a padding inside it. The content should be align with the title (h1).

Screenshot 2019-09-18 at 16 51 04

Still have a problem with the margin/content inside the wallets cards. There is a empty space under the initial balance.

Screenshot 2019-09-18 at 16 58 54

**Mobile version:**
You have a small issue on the Home's header when you look on a 768px width device.

Screenshot 2019-09-18 at 17 01 06

Don't forget to switch the position between the cards and the graph for the evolution of the distribution, graph first :)

Screenshot 2019-09-18 at 17 03 46

Otherwise that's it the rest looks great ;)

**Comment by EmmanuelDrouin** [comment]
We should have the same margin separating titles and paragraph. You did it great between the h1 and paragraph, but the rest of the titles (h2) are too close from the paragraph.

Screenshot 2019-09-20 at 11 31 52
Screenshot 2019-09-20 at 11 31 55
Screenshot 2019-09-20 at 11 32 02
Screenshot 2019-09-20 at 11 32 19
Screenshot 2019-09-20 at 11 33 42


When you click on the logo to go back to the home page something breaks.
Screenshot 2019-09-20 at 11 44 36

Also the logo in the footer should be clickable, like the logo in the header, and bring back to the home page.

You have an issue with this h2 in mobile, the size of the text is too small compare to the other h2.
Screenshot 2019-09-20 at 11 48 19

On mobile the contents and the numbers are stuck together, should add a bit of space ^^
Screenshot 2019-09-20 at 11 51 24

You can add more space between the buttons on mobile, like this it's gonna be complicated to click on these.
Screenshot 2019-09-20 at 11 52 31

Also you have a custom padding on the button that shouldn't be here as all the css for the buttons are directly in the components itself. 
Screenshot 2019-09-20 at 11 54 06
Screenshot 2019-09-20 at 11 54 15

On the distribution page on the mobile version the table is broken.
Screenshot 2019-09-20 at 11 58 01

On the locked wallets mobile version, add a global padding for the container, so the space between the top, left, right and bottom will be the same. Actually the padding top and bottom are smaller then the padding left and right.
Screenshot 2019-09-20 at 12 01 46
Screenshot 2019-09-20 at 12 01 52
Screenshot 2019-09-20 at 12 03 09

After these changes i think that's it we will be ready to go ;)

**Comment by blackinno** [comment]
- Fixed 
- Fix padding at the locked wallets page on a mobile version 
- Fix clicked at the logo on the menu
- Add space from h2 to paragraph
- Remove padding at button components
- Add the link to the image logo
- Add space on the total circulating supply

**Comment by blackinno** [comment]
closed #82, #83

**Pull request merged**
